version: '3.6'
services:
  app:
    build:
      context: .
    restart: always
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    volumes:
      - ./:/ormapp
  db:
    image: "postgres"
    environment: 
      POSTGRES_USER: shop
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"